<div id="VpnTile" class="tile <?php if ($this->_params['vpn_status'] == '100') echo 'connected'; ?>">
	<h3 id="VpnStatus">
		<?php
			if ($this->_params['vpn_status'] == '100')
				echo _('You are connected to a VPN');
			else
				/// TRANSLATORS: status context 
				echo _('Connecting to VPN');
		?>
	</h3>
    <div class="wrapper">
		<div class="progress"<?php if ($this->_params['vpn_status'] == '100') echo ' style="display: none;"'; ?>>
			<div id="vpnprogressbar" class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <?= $this->_params['vpn_status']?>%">
				<span class="sr-only">0% Complete (success)</span>
			</div>
		</div>

		<p style="margin-bottom: 12px;"><?php echo _('A Virtual Private Network creates an encrypted tunnel between the NetAidKit and a trusted network over the Internet.'); ?></p>
		<div style="<?php if ($this->_params['vpn_status'] != '100') echo 'display: none'; ?>" id="vpn_connected">
			<p><?php echo _('You are currently connected to VPN network:'); ?></p>
			<h5 style="margin-top: -1em; margin-bottom: 1em; margin-left: 12px;"><?= $this->_params['cur_vpn'] ?></h5>
		</div>
    </div>    
    <a class="btn btn-primary btn-lg btn-block btn-danger" data-toggle="modal" data-target="#vpnModal" href="#">
        <?php echo _('Disconnect from VPN'); ?>
    </a>
</div>

<?php include('modals/disconnect.phtml'); ?>
