<div class="tile">
    <h3><?php echo _('VPN');?></h3>
    <div class="wrapper">	
	<p><?php echo _('A Virtual Private Network creates an encrypted tunnel between the NetAidKit and a trusted network over the Internet.');?></p>
			<form id="vpnform">
				<label style="margin-left: 12px;">
					<a href="#" data-toggle="modal" data-target="#addVPN">
						<?php 
							/// TRANSLATORS: button context
							echo _('Add a VPN connection...');
						?>
					</a>
				</label><br>
				
				<?php
					$checked = 'checked="checked"';
					foreach ($this->_params['vpn_options'] as $config) {
						$file = $config['file'];
				?>
				<label style="margin-left: 12px;"><input type="radio" <?= $checked?> name="optionsRadios" id="optionsRadios2" value="<?php echo $file ?>" data-toggle="radio">&nbsp;&nbsp;&nbsp;<?php echo $config['title']; ?>&nbsp;&nbsp;&nbsp;<a class="open-deleteVPN" data-toggle="modal" data-id="<?php echo $file ?>" href="#deleteVPN"  style="text-decoration: none;"> <span class="fui-trash"></span></a> </label>
				<?php
					$checked = ''; /* Reset checked to empty for next items */ }
				?>
				<br><br>
			</form>
		</div>
		<a id="vpnConnectBtn" class="btn <?=($this->_params['cur_stage'] != STAGE_TOR && count($this->_params['vpn_options'])?'btn-primary':'btn-disabled')?> btn-lg btn-block" data-toggle="modal" <?=($this->_params['cur_stage'] != STAGE_TOR ? 'data-target="#vpnModal" href="online.html#"':'href=""');?>><?php echo _('Connect to VPN'); ?></a>
</div>
