<?php $i=1; foreach ($this->_params['wifi_list'] as $ssid => $enctype): ?>
    <label class="radio">
        <input type="radio" name="ssid" id="optionsRadios<?= $i++; ?>"<?php if ($enctype == 'Wired'): ?>checked="true"<?php endif;?>value="<?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?>" data-toggle="radio"><span class="fui-<?php if ($enctype == 'Wired'): ?>loop<?php elseif ($enctype <> 'Open'): ?>lock<?php else: ?>eye<?php endif;?>"></span> <?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?>
    </label>
<?php endforeach; ?>
