<?php $check = (($this->_params['broadcast_hidden_status'] == "1") ? '' : 'checked'); ?>

<div class="tile">
	<h3 style="margin-top: 0;"><?php echo _('Access point settings:'); ?></h3>
    <div class="login-form">
        <form action="/network/save" method="POST" id="network-form">
            <input type="checkbox" name="broadcast_ssid" value="broadcast_ssid" <?= $check ?> /> <?php echo _('Broadcast SSID'); ?>
            <a id="submit-network" class="btn btn-primary btn-lg btn-block"><?php echo _('Submit Change'); ?></a>
        </form>
    </div>
</div>
