<div class="tile">
	<h3 style="margin-top: 0;"><?php echo _('Stored networks:'); ?></h3>
	<p><?php echo _('Click on the play/pause button to enable/disable automatically reconnecting to the network. Click on the X to delete the network from your known network list.'); ?></p>
	<div style="position: relative;">
		<div id="wifi-list"><div class="spinner" style="margin-top: 45px;"><div class="spinner-loader"></div></div></div>
	</div>
</div>

<?php include ('wifimanager/modals/configure.phtml'); ?>
