<div class="tile">
	<h3 style="margin-top: 0;"><?php echo _('Stored networks:'); ?></h3>
	<p><?php echo _('Click on the gear button to edit the settings for a stored network. You may use the other button to enable or disable auto-connect.'); ?></p>
	<div style="position: relative;">
		<div id="wifi-list"><div class="spinner" style="margin-top: 45px;"><div class="spinner-loader"></div></div></div>
	</div>
</div>

<?php include ('wifimanager/modals/configure.phtml'); ?>
