<?php
		include('notify/js/notify.pjs');
		include('admin/js/admin.pjs');

		include('admin/menu.phtml');
		include('notify/notify.phtml');
		include('update/tiles/notification.phtml');

		$fblk = 'echo \'<div class="col-xs-12 col-md-6">\'; include(\'admin/tiles/tor.phtml\'); include(\'admin/tiles/vpn.phtml\'); echo \'</div>\';';
?>

<div class="row" style="margin-top: 30px;">
	<?php if(I18n::is_rtl()) eval($fblk); ?>
    <div class="col-xs-12 col-md-6">
        <img src="/img/logo/logo-nak-square.png">
        <?php echo _('<h3>Welcome!</h3>'); ?>
        <?php $this->_displayMessages('setup'); ?>
        <p><?php echo _('The NetAidKit is currently connected to the following network:'); ?></p>
        <?php include('admin/tiles/wireless.phtml'); ?>
        <?php include('admin/tiles/internet.phtml'); ?>
    </div>
	<?php if(!I18n::is_rtl()) eval($fblk); ?>
</div>
