<script type="text/javascript">
	<?php include 'network/js/network.pjs'; ?>
</script>

<?php include 'admin/menu.phtml'; ?>

<div class="row" style="margin-top: 30px;">
    <div class="col-xs-12 col-md-6">
        <?php echo _('
<h3>Network</h3>
<p>Here you can manage the NetAidKit network settings.</p>
            ');
        ?>
        <?php $this->_displayMessages('network'); ?>
	</div>
</div>
<div class="row">
    <div class="col-xs-12 col-md-6">
        <?php include ('network/tiles/wifimanager.phtml'); ?>
    </div>
    <div class="col-xs-12 col-md-6">
        <?php include ('network/tiles/network.phtml'); ?>
    </div>
</div>
