<label class="radio">
<table style="width: 100%;"><tbody>
<?php $i=1; foreach ($this->_params['wifi_list'] as $ssid => $properties): ?>
    <tr><td>
				<input type="radio" name="ssid" id="optionsRadios<?= $i++; ?>"<?php if ($properties['encryption'] == 'Wired'): ?>checked="true"<?php endif;?>value="<?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?>" data-toggle="radio"><span class="fui-<?php if ($properties['encryption'] == 'Wired'): ?>loop<?php elseif ($properties['encryption'] <> 'Open'): ?>lock<?php else: ?>eye<?php endif;?>"></span> <?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?>
		</td>
		<td style="text-align: right;"><?=($properties['encryption'] != 'Wired' ? '<div class="meter'.($properties['strength']<50?($properties['strength']<25?' red':' orange'):'').'"><span style="width: '.$properties['strength'].'%"></span></div>' :'') ?></td>
    </tr>
<?php endforeach; ?>
</tbody></table>
</label>
<div style="height: 1.5em;"></div>
